### ISSUE TITLE
Handle error code

### ISSUE THREAD

**Issue by bwrsandman** [McCzarny/upload-image#1]
I've been using this action for a few weeks now and I love it.
There are some times when the upload fails and the action seems to ignore this and return green.
Could there be anything done to catch these cases?

Example: https://github.com/openblack/openblack/runs/8000180023?check_suite_focus=true
```
Uploding an image screenshot-windows-latest-5d323461636979891c551b76adc0aa3977320cf0-release-four-gods.png to imgbb...
Error: Request failed with status code 400
    at createError (D:\a\_actions\McCzarny\upload-image\v1.0.0\webpack:\upload-image\node_modules\axios\lib\core\createError.js:16:1)
    at settle (D:\a\_actions\McCzarny\upload-image\v1.0.0\webpack:\upload-image\node_modules\axios\lib\core\settle.js:17:1)
    at IncomingMessage.handleStreamEnd (D:\a\_actions\McCzarny\upload-image\v1.0.0\webpack:\upload-image\node_modules\axios\lib\adapters\http.js:293:1)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data; boundary=--------------------------776791167703608273208821',
      'User-Agent': 'axios/0.24.0'
    },
    method: 'post',
    url: 'https://api.imgbb.com/1/upload?key=***',
    data: FormData {
      _overheadLength: 104,
      _valueLength: 2564884,
      _valuesToMeasure: [],
      writable: false,
      readable: true,
      dataSize: 0,
      maxDataSize: 2097152,
      pauseStreams: true,
      _released: true,
      _streams: [],
      'access-control-allow-origin': '*',
      'access-control-allow-headers': 'Cache-Control, X-Requested-With, Content-Type',
      'access-control-allow-methods': 'POST, GET, OPTIONS',
      'last-modified': 'Wed, 24 Aug 2022 17:00:09GMT',
      'cache-control': 'no-cache, must-revalidate',
      pragma: 'no-cache'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      url: 'https://api.imgbb.com/1/upload?key=***',
      data: [FormData]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: true,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /1/upload?key=*** HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: multipart/form-data; boundary=--------------------------776791167703608273208821\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'Host: api.imgbb.com\r\n' +
        'Connection: close\r\n' +
        'Transfer-Encoding: chunked\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/1/upload?key=***',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.imgbb.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: true,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { status_code: 400, error: [Object], status_txt: 'Bad Request' }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
undefined
```

**Comment by McCzarny** [comment]
Hello @bwrsandman, it's very nice to find out that someone is using my work :) You caught me on my holidays, that's why I'm responding so late. I will be happy to resolve the issues You created. The first PR is ready and soon I will merge it to propagate errors on upload.
